# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Business
    local_business_type: 'Science, Technology, Engineering'
    org_name: 'neonowl.systems'
    description: 'micro-enterprise design services'
  analytics:
    google_analytics: 'G-95HKQZHSCS'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "systems"
      # Logo filename in `assets/media/` folder
      filename: "logo.gif"
    button:
      enable: true
      text: "neonowl dot net"
      url: "https://www.neonowl.net/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} neonowl.systems'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
